### ISSUE TITLE
安装后没有反应

### ISSUE THREAD

**Issue by micaren** [jostar-y/emqx_plugin_mongodb#1]
安装后提示配置文件找不到

**Comment by jostar-y** [comment]
检查以下路径中配置文件是否存在
Default path： emqx/etc/emqx_plugin_mongodb.hocon
Attach to path: set system environment variables export EMQX_PLUGIN_MONGODB_CONF="absolute_path"

**Comment by ArdWang** [comment]
emqx_plugin_mongodb.hocon 这个文件要怎么编辑才会显示出来？
